server:
  port: 10418
spring:
  application:
    name: yuyu-seckill
  thymeleaf:
    cache: false #thymeleaf缓存关闭，因为不需要
  datasource: # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari: #springboot自带的数据库连接池（号称是最快的连接池）
      pool-name: DateHikariCP #自己起的连接池的名字
      minimum-idle: 5  #最小的空闲连接数
      idle-timeout:  1800000 #空闲连接存活的时间（默认600000   10分钟）
      maximum-pool-size: 10 #最大连接数  默认为10
      auto-commit: true #自动提交  从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间 ，0表示永久存活，默认1800000（30分钟）
      connection-timeout: 30000 #连接超时时间 默认30s
      connection-test-query: SELECT 1 #心跳机制 测试连接是否是可用的 一个查询语句
  data:
    redis:
#      host: 192.168.162.128
      host: localhost
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5
  rabbitmq:
    host: 192.168.162.128
    stream:
      username: guest
      password: guest
      virtual-host: /
      port: 5672
    listener:
      simple:
        #消费者最小/大数量
        concurrency: 10
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器  默认为true
        auto-startup: true
        #当发送的消息被拒绝时，是否重新进入队列（true  重新进入队列）
        default-requeue-rejected: true
    template:
      retry:
        #开启重试  默认false
        enabled: true
        #重试的时间,默认1000ms
        initial-interval: 1000ms
        #重试的最大次数
        max-attempts: 3
        #重试最大间隔时间  默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，比如multiplier: 2  ，第一次就等10s，第二次等20s，第三次等40s
        multiplier: 1
  web:
    #静态资源处理
    resources:
      #启用默认资源处理，默认是启用状态
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位是s
          max-age: 3600
      chain:
        #资源链启用缓存，默认启用
        cache: true
        #启用资源链，默认是关闭的
        enabled: true
        #启用压缩资源（gzip,brotli）解析，默认是禁用的
        compressed: true
        #启用H5应用缓存，默认是禁用的
        html-application-cache: true
      static-locations: classpath:/static/


  #    resources:
#      #    add-mappings: true
#      cache:
#        cachecontrol:
  #        max-age:
#  mvc:
#    static-path-pattern:
#但是既有配置文件又有配置类的情况下会优先加载配置类：WebMvcConfig


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml #配置××××Mapper.xml映射文件的位置
  type-aliases-package: com.example.pojo #返回的别名  配置Mybatis数据返回类型别名（默认是全类名）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Mybatis SQL 日志打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.seckill.mapper: debug

